theme = "fix_line_numbers"

[editor]
auto-pairs = false
bufferline = "always"
completion-replace = true
cursorcolumn = true
cursorline = true
gutters = ["diagnostics", "line-numbers", "diff"]
line-number = "relative"
rulers = [80]
true-color = true

[editor.indent-guides]
render = true
skip-levels = 2
# character = "⋮"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"
prefix-len = 2

# [editor.lsp]
# display-progress-messages = true
# display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.statusline]
mode.normal = "NORMAL"
mode.select = "SELECT"
mode.insert = "INSERT"
center = [ "version-control" ]

[keys.insert]
"C-," = [ ":insert-output echo -n '<-'", "append_mode", "collapse_selection" ]
"C-S-," = [ ":insert-output echo -n '<='", "append_mode", "collapse_selection" ]
"C-." = [ ":insert-output echo -n '->'", "append_mode", "collapse_selection" ]
"C-S-." = [ ":insert-output echo -n '=>'", "append_mode", "collapse_selection" ]
"A-S-down" = ["normal_mode", "extend_to_line_bounds", "yank", "open_below", "replace_with_yanked", "collapse_selection"]
"A-S-up" = ["normal_mode", "extend_to_line_bounds", "yank", "open_above", "replace_with_yanked", "collapse_selection"]

[keys.insert.j]
k = "normal_mode"

[keys.insert.j.j]
";" = "collapse_selection"
"," = "keep_primary_selection"

[keys.normal]
ins = "insert_mode"
X = "extend_line_above"
space."." = [ "collapse_selection", "insert_mode", "insert_newline", "normal_mode" ]
"A-S-down" = ["normal_mode", "extend_to_line_bounds", "yank", "open_below", "replace_with_yanked", "collapse_selection"]
"A-S-up" = ["normal_mode", "extend_to_line_bounds", "yank", "open_above", "replace_with_yanked", "collapse_selection"]
H = ["flip_selections", "move_char_left"]
"S-left" = ["flip_selections", "move_char_left"]
