theme = "fix_line_numbers"

[editor]
auto-pairs = false
bufferline = "always"
color-modes = true
completion-replace = true
cursorcolumn = true
cursorline = true
# Remove spacers arund line numbers
gutters = ["diagnostics", "line-numbers", "diff"]
line-number = "relative"
# I like the ruler on the line after 80, like a barrier
rulers = [81]
# Allow arbitrary hex codes in themes?
true-color = true

[editor.indent-guides]
render = true
# Skip first two indent guides because 0-2 tabs is pretty obvious already
skip-levels = 2
# character = "⋮"

[editor.inline-diagnostics]
# Show all LSP messages under relevant lines
cursor-line = "hint"
other-lines = "hint"
prefix-len = 2

# [editor.lsp]
# display-progress-messages = true
# display-inlay-hints = true

# [editor.soft-wrap]
# enable = true

[editor.statusline]
# Full words for mode names
mode.normal = "NORMAL"
mode.select = "SELECT"
mode.insert = "INSERT"

# Add git branch in middle
center = ["version-control"]

[keys.insert]
# Open language popup
C-space = "hover"

# Chords for left arrows
"C-," = [":insert-output echo -n '<-'", "append_mode", "collapse_selection"]
"C-S-," = [":insert-output echo -n '<='", "append_mode", "collapse_selection"]

# Chords for right arrows
"C-." = [":insert-output echo -n '->'", "append_mode", "collapse_selection"]
"C-S-." = [":insert-output echo -n '=>'", "append_mode", "collapse_selection"]

# Line duplication
# going to try not to use this in insert mode for now
# "A-S-down" = ["extend_to_line_bounds", "yank", "open_below", "replace_with_yanked"]
# "A-S-up" = ["extend_to_line_bounds", "yank", "open_above", "replace_with_yanked"]

[keys.insert.j]
# jk to leave insert mode
k = "normal_mode"

# jw to leave insert and save
w = ["normal_mode", ":write"]

# j; to get rid of distracting selections
";" = ["collapse_selection", "keep_primary_selection"]

# Trying out merging these for now
# [keys.insert.j.j]
# # jj to access selection commands
# ";" = "collapse_selection"
# "," = "keep_primary_selection"

[keys.normal]
# Open language popup
C-space = "hover"

# Add Ins shortcut for insert mode
ins = "insert_mode"

# Selections
X = "extend_line_above"

# Movement
H = ["flip_selections", "move_char_left"]
S-left = ["flip_selections", "move_char_left"]

# Insert newline at cursor
space."." = ["collapse_selection", "insert_mode", "insert_newline", "normal_mode"]

# Line duplication
A-S-down = ["extend_to_line_bounds", "yank", "paste_after"]
A-S-up = ["extend_to_line_bounds", "yank", "paste_before"]

# Line movement
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

# Ersatz code actions
[keys.normal.space.A]
# Sort exports
s = "@<C-s>ggf(ma(s\\w<ret>t<ret>:sort<ret><C-o><C-o>"

# Export symbol under cursor
e = "@<C-s>miwyggf(mmO, <esc>P<A-o>s\\w<ret>t<ret>:sort<ret><C-o><C-o><C-o>"

# Export symbol under cursor with (..)
E = "@<C-s>miwyggf(mmO, <esc>Pa(..)<esc><A-o>s\\w<ret>t<ret>:sort<ret><C-o><C-o><C-o>"
