inherits = "base16_default"

# default non-current line numbers are too dark to see
"ui.linenr" = "#555555"

# make "NORMAL" label stand out from status line
"ui.statusline.normal" = { bg = "#666666" }

# default comment color is too dark
"comment" = { fg = "#707070"}
type = "#efd64b"
keyword = "#957bbe"

"variable" = "#e05a4f"

# make rule more subtle
"ui.virtual.ruler" = { bg = "#333333" }

# for some reason, whitespace is rendering italic by default,
#   which affects indent guides
# explicitly setting modifiers to an empty array isn't necessary
#   but it's a reminder
"ui.virtual.indent-guide" = { fg = "#005a5a" }
"ui.virtual.whitespace" = { fg = "#00a0a0", modifiers = [] }
"ui.virtual.wrap" = { fg = "#00ffff" }

# make hints light green instead of gray
hint = { fg = "#c5ffa8" }

# make cursors brighter, distinct colors
["ui.cursor"]
fg = "#fff176"
modifiers = [ "reversed", "italic" ]

["ui.cursor.primary"]
fg = "#ef5350"
modifiers = [ "reversed" ]

# make selection colors similar to cursor colors
["ui.selection"]
fg = "#bdbc7b"
# add italic to secondary selections to make more distinct
modifiers = [ "reversed", "italic" ]

["ui.selection.primary"]
fg = "#eb8c8a"
modifiers = [ "reversed" ]
