inherits = "base16_default"
"ui.linenr" = "#555555"
"ui.linenr.selected" = "#cccccc"
"ui.statusline.normal" = { bg = "#666666" }
"comment" = "#707070"
"ui.virtual.ruler" = { bg = "#333333" }
hint = { fg = "#c5ffa8" }
